### ISSUE TITLE
[BUG] Domain template JwtAccess import not found

### ISSUE THREAD

**Issue by p-mcgowan** [acrontum/openapi-nodegen-typescript-server#4]
**Describe the bug**
Newly generated domain file imports an unused and non-existent `JwtAccess` interface

**To Reproduce**

1. Add routes to api.yml
```
  /test:
    get:
      tags:
        - test
      summary: test
      operationId: testGet
      description: |
        Not a test
      responses:
        '200':
          description: Succeed
```
2. Generate with nodegen
3. tsc should report errors for new domains
```
import { JwtAccess } from '@/http/nodegen/interfaces/JwtAccess';
                                                      ^ does not exist
```
**Expected behavior**
Presumably if the interface is actually unused and does not exist, this line should not be there

**Node & NPM version**
Node 13.13.0 (also 12.16.2)
NPM 6.14.4
openapi-nodege: 5.1.8 (also 5.1.7)

**Operating system:**
OS: Ubuntu
Version: 18.04.4

**Additional context**
https://github.com/acrontum/openapi-nodegen-typescript-server/blob/1e0738e2db4a797e8698f0944d03b0b23fd743df/src/domains/___stub.ts.njk#L2

Causes tsc to error with module not found

**Comment by Acrontum-Carmichael** [comment]
Hi @p-mcgowan the jwt access interface is generated only when you add a definition into the api file: https://github.com/acrontum/openapi-nodegen-typescript-server#nodegenrc-helpers

The interface is only for internal use of the API, so the definition will not be used by any paths.

The interface cannot be auto-generated as the content are unique to an api.

Here is an example:
```
type: object
description: >
  This model will never be passed in this from the front and backend or vice versa.
  This represents the payload of the access jwt token which is made available to the req.jwtData
  This allows the interface to be made by generate-it
required:
  - _id
  - active
  - createdAt
  - disciplineIds
  - email
  - firstName
  - lastName
  - role
  - title
  - updatedAt
properties:
  _id:
    type: string
  active:
    type: boolean
  createdAt:
    type: string
  disciplineIds:
    type: array
    items:
      type: string
  email:
    type: string
  firstName:
    type: string
  lastName:
    type: string
  role:
    type: string
  title:
    type: string
  updatedAt:
    type: string
```
